Swapneel refactor
MaMMoS-project/mochada_kit pull request #3
Opened 2024-10-19 09:57 UTC by swapneelap

My nitpicky refactor: no need to accept all the changes!

2024-10-23 09:37 UTC, tgwoodcock requested changes
Fantastic stuff @swapneelap! Love the changes - they make for a much cleaner interface.

I just have a few small comments which need minor changes and we can discuss about these.

2024-10-23 09:37 UTC, tgwoodcock commented on src/mochada_kit/__init__.py
> +    pathlib.Path(__file__).absolute().parent.parent.joinpath("themes").as_posix()
Here we need to go up one more parent to get to the themes dir.

2024-10-23 09:37 UTC, tgwoodcock commented on src/mochada_kit/cli.py
> +#         make_config(puml_path=args.puml_path)
Let's remove all this old stuff,

2024-10-23 09:37 UTC, tgwoodcock commented on src/mochada_kit/config.py
> +        raise OSError(error)
How about downgrading the error to a warning and returning None? That way, we avoid the case that the user is forced to set the config in order to be able to import the module mochada_kit.running.

We should also update the error/warning message to the new format of your cli (the flag -c is no longer valid and we need the argument config instead). I would also like to have the name of the cli command as "mochada_kit" (with underscore, just to keep it the same as the package name).

2024-10-23 09:37 UTC, tgwoodcock commented on pyproject.toml
> +mochadakit = "mochada_kit.cli:cli"
I'd like to have the name of the project script as "mochada_kit" with the hyphen, just to keep it the same as the package name.

2024-10-23 09:37 UTC, tgwoodcock commented on examples/make_workflow_diagram.ipynb
> +      "/home/swapneel/Projects/Forks/mochada_kit/src/themes\n"
I don't know if this matters here but the themes dir is actually outside the src dir (see other comment about the extra parent for the _THEMES_DIR in __init_.py).

2024-11-07 09:31 UTC, swapneelap commented
Hello @tgwoodcock, I have ad the changes in according to your comments. If you think they are good, please merge the pull request.

2024-11-07 12:23 UTC, merged